version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: envoy-grpcweb
    network_mode: "host"        # dùng network của host → thấy localhost:50051
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "info"]
    restart: unless-stopped
